### PR TITLE
Adr/dependabot config

### PR DESCRIPTION
**Pull request by RobjS**
This PR:

* Adds a new ADR for using `dependabot.yml` files to configure GitHub security alerts (and Dependabot PRs) to make them less noisy, but preserve the valuable signal amongst the noise
* Adds a missing `.md` extension to the previous ADR

### CODE REVIEW

**Comment by RobjS** [comment]
Tagging in @rjw1, @erbridge, @matthewpassmore, @serena-piccioni and @brent-dxw for opinions on this.

**Comment by rjw1** [comment]
:+1:

**Review by erbridge — APPROVED** [review]
I agree.

**Review by serena-piccioni — APPROVED** [review]
👍🏻

**Comment by brent-dxw** [comment]
👍

**Pull request merged**
