### PR TITLE
Test classes for type safety with Psalm

### PR DESCRIPTION
**Pull request by mallorydxw**
- composer require --dev vimeo/psalm
- Add psalm.xml
- GitHub Actions: Add psalm test

Resolves: https://github.com/dxw/wordpress-template/issues/18

- [x] Wait until #31 is merged

### CODE REVIEW

**Comment by mallorydxw** [comment]
@RobjS Are you able to look at this one too, when you have a moment?

**Comment by RobjS** [comment]
@mallorydxw I wonder how we should handle the possibility of "mixed" parameter types that WordPress often deals in; to pick a random example: https://codex.wordpress.org/Plugin_API/Filter_Reference/pre_comment_approved, where the first argument could be either a string or an integer, so cannot be type hinted.

From some quick local testing, I've found a couple of options:

a) Suppress those errors for the class in question:

```
<issueHandlers>
  <MissingParamType>
    <errorLevel type="suppress">
      <file name="x.php"/>
    </errorLevel>
  </MissingParamType>
</issueHandlers>
```

b) Use DocBlock annotations, e.g.

```
/** @param mixed $mixedParam */
    public function doSomething($mixedParam) : string
    {
        return 'foo';
    }
```

I think my preference would be a), as using DocBlock annotations only intermittently would seem confusing, and I've no desire to start using them everywhere. But the downside to that is that the entire file will then not be tested for missing param types, and the more exceptions we have, the less valuable (and more hassle to maintain) the tool is. What do you think?

Incidentally, it looks like the "mixed" type will be supported in PHP 8: https://github.com/PHPCompatibility/PHPCompatibility/pull/1217

**Comment by mallorydxw** [comment]
> But the downside to that is that the entire file will then not be tested for missing param types

Yeah, and at that point what's the point of even using Psalm?

> What do you think?

We already need to use docblocks in places where PHP doesn't allow declaring types. For example in instance/class variables:

https://github.com/dxw/cidr/blob/main/src/BlockBase.php#L7-L11

They also allow using constructions that PHP doesn't recognise such as `int|null`:

https://github.com/dxw/cidr/blob/main/src/RangeBase.php#L13-L17

I think using docblocks is our only real option since the alternative is pretty much turning off most of the type checking.

**Comment by mallorydxw** [comment]
Let's get the rest of the team in here. For some reason it's not letting me add these folks as reviewers, so I'll @ everybody.

@anthonyomalley @calumryan @dxw-serena @mattymaxwell

**Pull request closed without merging**
